#### Introduction to Numpy:
------------------------------------
##### NumPy is a Python library used for working with arrays.
##### It also has functions for working in domain of linear algebra, fourier transform, and matrices.
##### NumPy stands for Numerical Python.

#### Why to use Numpy:
---------------------------------
##### Speed: NumPy arrays are significantly faster than standard Python lists for numerical operations, as it is written in both Python and C language
##### Memory Efficiency: NumPy arrays consume less memory than Python lists, especially when dealing with large datasets, due to their homogeneous data type and contiguous memory allocation.

#### ndarray:
-------------------------------------------
##### NumPy introduces the ndarray, a multi-dimensional array object that is central to its functionality. This allows for efficient storage and manipulation of numerical data in various dimensions.
##### It provides a wide range of functions for creating, manipulating, and performing operations on these arrays.

In [2]:
print([1,2,3,4,5] + [1,2,3,4,5])

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
li = [2,3,4,5,6,7]
print(li)

type(li)

[2, 3, 4, 5, 6, 7]


list

In [3]:
#pip install numpy
import numpy as np
#Converts a simple list to array
arr = np.array([2,3,5,6,7,8])

print(arr)

type(arr)

[2 3 5 6 7 8]


numpy.ndarray

In [4]:
#pip install numpy
import numpy as np
#Converts a simple tuple to array
arr = np.array((1, 2, 3, 4, 5))

print(arr)

type(arr)

[1 2 3 4 5]


numpy.ndarray

#### Dimensions of array:
---------------------------------
##### 1D Array: A one-dimensional array has a single axis. It can be visualized as a list of elements.
##### 2D Array: A two-dimensional array has two axes. It can be visualized as a table or a matrix with rows and columns.
##### Higher-Dimensional Arrays: NumPy supports arrays with any number of dimensions. For example, a 3D array might represent a collection of 2D matrices, and its shape would reflect the sizes along all three axes.

#### ndim is the property to check diemnsion of numpy array

In [5]:
#0-dimension
import numpy as np

arr = np.array(70)

print(arr)

print(arr.ndim)

70
0


In [6]:
#one-dimension array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr.ndim)

[1 2 3 4 5]
1


In [7]:
#two-dimension array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
#three-dimension array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6], [4,7,8]]])

print(arr)

print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [4 7 8]]]
3


In [9]:
#three-dimension array
import numpy as np

arr = np.array([[[[1, 2, 3], [4, 5, 6], [4,7,8], [4,6,8]]]])

print(arr)

print(arr.ndim)

[[[[1 2 3]
   [4 5 6]
   [4 7 8]
   [4 6 8]]]]
4


#### ndmin: This argument explicitly sets the minimum number of dimensions for the resulting array.

In [10]:
#three-dimension array
import numpy as np

arr = np.array([1, 2, 3 ,4 ,5], ndmin=5)

print(arr)

print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


#### ndim:
This integer attribute represents the number of dimensions (or axes) of the array. For example, a 1D array (vector) has ndim = 1, while a 2D array (matrix) has ndim = 2.
#### size:
This integer attribute represents the total number of elements in the array. It is the product of the elements in the shape tuple.
#### shape:
the shape attribute returns a tuple of integers that gives the size of the array in each dimension.
#### dtype:
This attribute specifies the data type of the elements within the array. All elements in a NumPy array must have the same data type.
#### itemsize:
This integer attribute indicates the size in bytes of each individual element in the array. For example, if the dtype is int64, itemsize would typically be 8 bytes.
#### nbytes:
This integer attribute represents the total number of bytes consumed by the array in memory. It is calculated as size * itemsize.
#### T:
This attribute returns the transpose of the array, effectively swapping axes.
#### flat:
This attribute provides an iterator that allows iterating over all elements of the array as if it were a 1D array.

In [11]:
import numpy as np

array1 = np.array([[1, 2, 3],
                 [6, 7, 8]])

# return total number of elements in array1
print(array1.size)

6


In [12]:
import numpy as np

array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)

(2, 3)


In [15]:
import numpy as np

# create an array of integers
array1 = np.array([6, 7, 8])

# check the data type of array1
print(array1.dtype)

int64


In [18]:
import numpy as np

# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)  # prints 8
print(array2.itemsize)  # prints 4

8
4


In [ ]:
import numpy as np

# Create a NumPy array
arr = np.zeros((3, 5), dtype=np.float64)

# Get the total bytes consumed by the elements
total_bytes = arr.nbytes
print(f"Total bytes consumed by array elements: {total_bytes}")

Total bytes consumed by array elements: 120


In [19]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original array:")
print(arr)

# Get the transpose using .T
transposed_arr = arr.T

print("\nTransposed array using .T:")
print(transposed_arr)

Original array:
[[1 2 3]
 [4 5 6]]

Transposed array using .T:
[[1 4]
 [2 5]
 [3 6]]


In [20]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Iterate using flat
print("Iterating using flat:")
for element in arr.flat:
    print(element)

# Access elements using flat
print("\nAccessing elements using flat:")
print(f"Element at index 0: {arr.flat[0]}")
print(f"Element at index 4: {arr.flat[4]}")

Iterating using flat:
1
2
3
4
5
6

Accessing elements using flat:
Element at index 0: 1
Element at index 4: 5


#### numpy.linalg: Provides functions for linear algebra operations, including matrix multiplication, inversion, determinant calculation, eigenvalue decomposition, and solving linear equations.
#### numpy.fft: Offers functions for computing Fast Fourier Transforms (FFTs) and related operations, useful in signal processing and other domains.
#### numpy.random: Contains tools for generating pseudo-random numbers, including various probability distributions (e.g., normal, uniform, binomial).
#### numpy.ma: Supports masked arrays, which are arrays that can have "masked" or invalid data points, allowing operations to ignore these values.
#### numpy.char: Provides legacy string operations for fixed-width string arrays.
#### numpy.matlib: Offers functions that primarily support numpy.matrix instances, which are a specialized 2D array type (though ndarray is generally preferred for most uses).
#### numpy.polynomial: Contains classes and functions for working with polynomials.
#### numpy.testing: Provides utilities for testing NumPy code.
#### numpy.distutils: Offers build system support for NumPy extensions (though this is primarily for internal use and development).
#### numpy.f2py: A tool for connecting Fortran code with Python, allowing the use of Fortran routines within NumPy.