In [6]:
import numpy as np
matrix_a = np.array([[1, 2], [3, 4]])
vector_b = np.array([5, 6])

In [4]:
import numpy as np

# Define the two matrices as NumPy arrays
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_b = np.array([[7, 8, 9],
                     [10, 11, 12]])

# Add the matrices using the + operator
result_matrix = matrix_a + matrix_b

# Print the resulting matrix
print(result_matrix)

result_matrix = np.add(matrix_a,matrix_b)

print(result_matrix)

[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]


In [2]:
import numpy as np

# Create two matrices
matrix_a = np.array([[5, 8], [7, 10]])
matrix_b = np.array([[2, 4], [3, 6]])

# Subtract the matrices
matrix_c = matrix_a - matrix_b

print("Matrix C (A - B):")
print(matrix_c)

#matrix_c = np.subtract(matrix_a,matrix_b)

Matrix C (A - B):
[[3 4]
 [4 4]]


In [7]:
result_dot = np.dot(vector_b, vector_b)
print(result_dot)

61


In [8]:
import numpy as np

# Define two 3D vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Compute the cross product
cross_product_result = np.cross(vector_a, vector_b)

print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Cross Product: {cross_product_result}")

Vector A: [1 2 3]
Vector B: [4 5 6]
Cross Product: [-3  6 -3]


In [9]:
result_matmul = matrix_a @ matrix_a

print(result_matmul)

#result_matrix = np.matmul(matrix_a, matrix_a)

[[ 7 10]
 [15 22]]


In [12]:
from numpy import linalg
from numpy import linalg as la
determinant = la.det(matrix_a)
np.set_printoptions(precision=4)
print(f"The deteminant of matrix is:{determinant:.4f}")

The deteminant of matrix is:-2.0000


In [14]:
import numpy as np

arr = np.array([1.23456789, 0.987654321])
np.set_printoptions(precision=4) # Set global precision to 4 decimal places
print(arr)

[1.2346 0.9877]


In [15]:
import numpy as np

arr = np.array([1.23456789, 0.987654321])
rounded_arr = np.around(arr, decimals=4)
print(rounded_arr)

[1.2346 0.9877]


In [17]:
inverse_matrix = la.inv(matrix_a)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
transposed_matrix = np.transpose(matrix_a)
print(transposed_matrix)

[[1 3]
 [2 4]]


In [20]:
eigenvalues, eigenvectors = la.eig(matrix_a)
print(eigenvalues)
print(eigenvectors)

[-0.3723  5.3723]
[[-0.8246 -0.416 ]
 [ 0.5658 -0.9094]]


In [21]:
matrix_rank = la.matrix_rank(matrix_a)
print(matrix_rank)

2


In [23]:
matrix_power_result = la.matrix_power(matrix_a, 3) # matrix_a cubed
print(matrix_power_result)

[[ 37  54]
 [ 81 118]]
