#### The numpy.random module provides various functions for generating random numbers and performing random operations.

In [2]:
import numpy as np
from numpy import random as rnd

In [4]:
#numpy.random.rand(d0, d1, ..., dn): Generates an array of the specified shape filled with random floats from a uniform distribution over [0, 1)
rand_value_float = rnd.rand()
print(f"Single random value float: {rand_value_float}")
print("------------------------------------------")
# 1D array of 5 random floats
rand_array_1d = rnd.rand(5)
print(f"1D array of random floats: {rand_array_1d}")
print("------------------------------------------")
# 2D array (2x3) of random floats
rand_array_2d = rnd.rand(2, 3)
print(f"2D array of random floats:\n{rand_array_2d}")

Single random value float: 0.26770805372932505
------------------------------------------
1D array of random floats: [0.28640085 0.62282448 0.60357392 0.14782266 0.34050092]
------------------------------------------
2D array of random floats:
[[0.59825829 0.55394188 0.08609767]
 [0.99266926 0.66228023 0.30042007]]


In [15]:
#numpy.random.randint(low, high=None, size=None, dtype=int): Generates random integers from [low, high) (or [0, low) if high is None).
# Single random integer between 0 and 9
rand_int = np.random.randint(10)
print(f"Single random integer: {rand_int}")

# Array of 5 random integers between 1 and 10 (inclusive)
int_array = np.random.randint(1, 11, size=7, dtype=int)
print(f"Array of random integers: {int_array}")

# 2D array (3x4) of random integers between 0 and 99
int_array_2d = np.random.randint(100, size=(3, 4))
print(f"2D array of random integers:\n{int_array_2d}")

Single random integer: 2
Array of random integers: [ 8  9  8  5 10  1  4]
2D array of random integers:
[[35 50 45 11]
 [71 54 20 72]
 [83 76 63 85]]


In [27]:
#numpy.random.choice(a, size=None, replace=True, p=None): Generates a random sample from a given 1-D array or list.

# Choose a single random element from a list
elements = ['apple', 'banana', 'cherry']
chosen_element = np.random.choice(elements, size=2)
print(f"Chosen element: {chosen_element}")

# Choose 3 random elements with replacement
chosen_multiple = np.random.choice(elements, size=3, replace=True)
print(f"Chosen multiple elements (with replacement): {chosen_multiple}")

# Choose 2 random elements without replacement
chosen_unique = np.random.choice(elements, size=2, replace=False)
print(f"Chosen unique elements (without replacement): {chosen_unique}")

# Choose with probabilities
weighted_choice = np.random.choice(elements, p=[0.6, 0.3, 0.1])
print(f"Weighted choice: {weighted_choice}")

Chosen element: ['banana' 'banana']
Chosen multiple elements (with replacement): ['apple' 'apple' 'cherry']
Chosen unique elements (without replacement): ['apple' 'cherry']
Weighted choice: apple


In [30]:
#numpy.random.shuffle(x): Modifies a sequence in-place by shuffling its contents.
arr = np.array([1, 2, 3, 4, 5])
rnd.shuffle(arr)
print(f"Shuffled array: {arr}")

Shuffled array: [2 4 1 3 5]


In [35]:
#numpy.random.seed(seed): Initializes the random number generator. Using the same seed will produce the same sequence of random numbers.
np.random.seed(100)
print(f"Random number with seed 42 (first call): {np.random.rand()}")
np.random.seed(30) # Resetting the seed
print(f"Random number with seed 42 (second call): {np.random.rand()}")

Random number with seed 42 (first call): 0.5434049417909654
Random number with seed 42 (second call): 0.644143536068335


#### numpy.ones(shape, dtype=None, order='C')
#### numpy.zeros(shape, dtype=float, order='C')
##### C-style row-major order, while 'F' represents Fortran-style column-major order.

In [38]:
#np.ones() and np.zeros()
ones_array = np.ones(5,dtype=int)
print(f"Array of ones: {ones_array}")

zeros_array = np.zeros(3,dtype=int)
print(f"Array of zeros: {zeros_array}")

Array of ones: [1 1 1 1 1]
Array of zeros: [0 0 0]


In [41]:
import numpy as np
arr_zeros_int = np.zeros((2, 2), dtype=int)
print(arr_zeros_int)

arr_ones_int = np.ones((2, 3), dtype=int)
print(arr_ones_int)

[[0 0]
 [0 0]]
[[1 1 1]
 [1 1 1]]


In [43]:
import numpy as np
arr_ones_float32 = np.ones((1, 4), dtype=float)
print(arr_ones_float32)

[[1. 1. 1. 1.]]


In [44]:
import numpy as np
arr_fives = np.ones(4) * 5
print(arr_fives)

[5. 5. 5. 5.]


In [5]:
import numpy as np

# Create a default random number generator
rng = np.random.default_rng(seed=50)
print(rng)
print("------------------------------------------------------------------------")

# Uniform Distribution (floats between 0 and 1)
uniform_samples = rng.random(size=5)
print(f"Uniform samples: {uniform_samples}")

print("------------------------------------------------------------------------")

# Uniform Distribution (integers within a range)
# Generates integers from 'low' (inclusive) to 'high' (exclusive)
randint_samples = rng.integers(low=1, high=10, size=5)
print(f"Random integers: {randint_samples}")

print("------------------------------------------------------------------------")

# Normal (Gaussian) Distribution
# loc: mean, scale: standard deviation
normal_samples = rng.normal(loc=0, scale=1, size=5)
print(f"Normal samples: {normal_samples}")

print("------------------------------------------------------------------------")

# Binomial Distribution
# n: number of trials, p: probability of success
binomial_samples = rng.binomial(n=10, p=0.5, size=5)
print(f"Binomial samples: {binomial_samples}")

print("------------------------------------------------------------------------")

# Poisson Distribution
# lam: average number of events
poisson_samples = rng.poisson(lam=5, size=5)
print(f"Poisson samples: {poisson_samples}")

print("------------------------------------------------------------------------")

p = 0.7  # Probability of success
num_trials = 10  # Number of Bernoulli trials to simulate

bernoulli_trials = rng.binomial(n=1, p=p, size=num_trials)
print(bernoulli_trials)

Generator(PCG64)
------------------------------------------------------------------------
Uniform samples: [0.78742269 0.83366933 0.54790446 0.9734491  0.23683356]
------------------------------------------------------------------------
Random integers: [3 6 7 1 9]
------------------------------------------------------------------------
Normal samples: [ 0.24475037  0.17981042 -1.34158469 -0.18198125 -0.54216087]
------------------------------------------------------------------------
Binomial samples: [3 3 8 5 7]
------------------------------------------------------------------------
Poisson samples: [2 3 6 4 5]
------------------------------------------------------------------------
[1 0 1 1 1 0 1 0 1 1]
