In [5]:
"""Creation of arrays"""
#Array creation
import numpy as np

# From a list
arr1 = np.array([1, 2, 3, 4])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr3d = np.array([[[[1, 2, 3], [4, 5, 6], [5,6,8]]]])
print(arr1)
print(arr2d)
print(arr3d)

# Zeros array
zeros_arr = np.zeros((2, 3)) # 2x3 array of zeros
print(zeros_arr)
# Ones array
ones_arr = np.ones((3, 2)) # 3x2 array of ones
print(ones_arr)

# Array with a range of values
range_arr = np.arange(0, 10, 2) # 0, 2, 4, 6, 8
print(range_arr)

# Evenly spaced values
linspace_arr = np.linspace(0, 1, 6)
print(linspace_arr)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[[1 2 3]
   [4 5 6]
   [5 6 8]]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1. ]


In [20]:
"""Manipulating arrays"""
arr = np.array([[1, 2, 3,], [4, 5, 6]])
print(arr)

# Reshaping
reshaped_arr = arr.reshape((3, 2))
#print(reshaped_arr)

# Transposing
transposed_arr = arr.T
#print(transposed_arr)

# Concatenation
arr_c = np.array([7, 8, 9])
concatenated_arr = np.concatenate((arr, arr_c.reshape(1, -1)), axis=0)
print(concatenated_arr)

# Splitting
split_arr = np.split(arr, 2, axis=0) # Split into two sub-arrays along rows
print(split_arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [23]:
"""Aggregation of arrays"""
arr_agg = np.array([1, 5, 2, 8, 3])

# Sum
total_sum = np.sum(arr_agg)
print(total_sum)

# Mean
average = np.mean(arr_agg)
print(average)

# Max and Min
max_val = np.max(arr_agg)
min_val = np.min(arr_agg)
print(max_val)
print(min_val)

19
3.8
8
1


In [ ]:
"""Arithmetic operations of arrays"""
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Addition
add_result = arr_a + arr_b

# Subtraction
sub_result = arr_b - arr_a

# Multiplication
mul_result = arr_a * arr_b

# Division
div_result = arr_b / arr_a

# Exponentiation
pow_result = arr_a ** 2

In [29]:
"""Slicing and Indexing"""
arr = np.arange(10,20)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:5])

Array: [10 11 12 13 14 15 16 17 18 19]
Element at 7th index is: 17
Elements from 3rd to 5th index are: [13 14 15]
Elements up to 4th index are: [10 11 12 13 14]


In [30]:
#The array is getting formed upto 20th random element with spacing 2
arr = np.arange(0,20,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset
print("Elements at 2nd, 4th, 6th and 9th index are:", arr[[2,4,6,8]]) # Pass a list as a index to subset

New array: [ 0  2  4  6  8 10 12 14 16 18]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]
Elements at 2nd, 4th, 6th and 9th index are: [ 4  8 12 16]


In [31]:
"""Indexing and Slicing:"""
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[1]) # Access element at index 1

20


In [32]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # Elements from index 1 up to (but not including) 4

[20 30 40]


In [33]:
"""Boolean Indexing: Selecting elements based on a condition."""
import numpy as np
arr = np.array([1, 5, 2, 8, 3])
filtered_arr = arr[arr > 3]
print(filtered_arr)

[5 8]
