In [10]:
#We all understood creating matrix with passing arrays with 2-d and 3-d
#Now we will understand on how to create matrix using random functions
import numpy as np
from numpy.random import randint as ri
mat = np.array(ri(10,100,20)).reshape(4,5)
print(mat)

[[99 23 34 88 40]
 [27 25 70 52 95]
 [86 89 91 79 18]
 [32 50 61 41 18]]


In [11]:
"""Indexing Individual Elements:
Access elements using [row_index, column_index]. Remember, indexing is 0-based."""
# Access the element at row 0, column 0 (value 1)
num_0_0 = mat[0, 0]
print(f"\nElement at (0, 0): {num_0_0}")

# Access the element at row 2, column 3 (value 12)
num_2_3 = mat[2, 3]
print(f"Element at (2, 3): {num_2_3}")


Element at (0, 0): 99
Element at (2, 3): 79


In [13]:
"""Use [start_row:end_row:step_row, :] to select rows. The : for columns means "all columns"."""
# Select the first row
first_row = mat[0, :]
print(f"\nFirst row: {first_row}")

# Select the last two rows
last_two_rows = mat[2:, :]
print(f"Last two rows:\n{last_two_rows}")

# Select rows with a step of 2 (rows 0 and 2)
even_rows = mat[::2, :]
print(f"Even rows:\n{even_rows}")


First row: [99 23 34 88 40]
Last two rows:
[[86 89 91 79 18]
 [32 50 61 41 18]]
Even rows:
[[99 23 34 88 40]
 [86 89 91 79 18]]


In [16]:
"""Slicing Columns:
Use [:, start_col:end_col:step_col] to select columns. The : for rows means "all rows"."""
# Select the second column
second_column = mat[:, 1]
print(f"\nSecond column: {second_column}")

# Select the first and third columns
first_and_third_cols = mat[:, [0, 2]]
print(f"First and third columns:\n{first_and_third_cols}")


Second column: [23 25 89 50]
First and third columns:
[[99 34]
 [27 70]
 [86 91]
 [32 61]]


In [20]:
# Select the 2x2 sub-matrix from row 1 to 2, column 1 to 2
sub_matrix = mat[1:3, 1:3]
print(f"\n2x2 sub-matrix:\n{sub_matrix}")

# Select elements from rows 0 and 2, and columns 0 and 3
specific_elements = mat[[0, 2], [0, 3]] # This performs advanced indexing, resulting in a 1D array
print(f"Specific elements (advanced indexing): {specific_elements}")

# To get a sub-matrix from specific rows and columns, use slicing for both:
# For example, rows 0 and 2, and columns 0 to 2
rows_0_2_cols_0_2 = mat[[0, 2], 0:3] # This also uses advanced indexing for rows, but slicing for columns
print(f"Sub-matrix using mixed indexing:\n{rows_0_2_cols_0_2}")


2x2 sub-matrix:
[[25 70]
 [89 91]]
Specific elements (advanced indexing): [99 79]
Sub-matrix using mixed indexing:
[[99 23 34]
 [86 89 91]]


In [22]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 70
Entire row at index 2: [86 89 91 79 18]
Entire column at index 3: [88 52 79 41]


In [23]:
print("\nSubsetting sub-matrices\n")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[52 95]
 [79 18]]


In [24]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[23 88]
 [25 52]]


In [25]:
mat[[0,2],[1,4]]

array([23, 18])

In [26]:
mat[[1,2],]

array([[27, 25, 70, 52, 95],
       [86, 89, 91, 79, 18]])

In [27]:
mat[[1,2],[1,3]]  # row,col

array([25, 79])

In [31]:
mat[[0,2],[[1,4],[2,3]]]

array([[23, 18],
       [34, 79]])

In [30]:
mat[0:2,[[1,3],[1,4]]]

array([[[23, 88],
        [23, 40]],

       [[25, 52],
        [25, 95]]])